language: ruby
rvm:
  - 2.3.3
cache: bundler
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install -y clang
install:
  - travis_retry bundle update
  - gem install pdd
script:
  - pdd -f /dev/null
  - rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
