language: ruby
rvm:
  - 2.3.3
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry bundle update
  - gem install pdd
  - apt-get install clang -y
script:
  - pdd -f /dev/null
  - rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
