language: ruby
rvm:
  - 2.3.3
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry bundle update
  - sudo apt-get install cppcheck
script:
  - cppcheck --enable=all --quiet --suppress=unusedFunction .
  - rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
